name: Tauri Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node dependencies
        run: npm i

      - name: Install Rust & Tauri deps
        run: |
          rustup update stable
          rustup target add x86_64-pc-windows-msvc
          npm install -g @tauri-apps/cli

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Build Tauri app
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        run: npm run tauri build

      - name: Upload app build
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-app
          path: src-tauri/target/release/bundle
