name: Tauri Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Node dependencies
        run: npm ci

      - name: Install Rust & Tauri deps
        run: |
          rustup update stable
          rustup target add x86_64-pc-windows-msvc
          npm install -g @tauri-apps/cli

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in
        run: npx semantic-release

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload app build
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-app
          path: src-tauri/target/release/bundle
